services:
  gedmo.listener.timestampable:
          class: Gedmo\Timestampable\TimestampableListener
          tags:
              - { name: doctrine.event_subscriber, connection: default }
          calls:
              - [ setAnnotationReader, [ '@annotation_reader' ] ]
  twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
