services:
    #functionality services
    news.antispam:
        class: NewsBundle\AntiSpam\AntiSpam
        arguments:
            - 50
    #twig extensions services
    news.twig_extension:
            class: NewsBundle\Extension\NewsExtension
            public: false
            arguments: ['@translator']
            tags:
                - { name: twig.extension }
    #provider services
    news.comment.provider:
        class: NewsBundle\Provider\CommentProvider
    #listener services
    news.comment.listener:
        class: NewsBundle\Listener\CommentListener
        arguments:
            - "@news.comment.provider"
        tags:
            - { name: kernel.event_listener, event: comment.creation, method: onCommentCreation }
    #repository services
    news.post_repository:
        class: NewsBundle\Repository\PostRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - NewsBundle\Entity\Post
    news.comment_repository:
        class: NewsBundle\Repository\CommentRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - NewsBundle\Entity\Comment
    news.user_repository:
        class: NewsBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - NewsBundle\Entity\User
    #form services
    news.form.comment:
            class: Symfony\Component\Form\Form
            factory: ['@form.factory', createNamed]
            arguments: [comment_name, 'NewsBundle\Form\CommentType', null , { validation_groups: [Default] }]
    news.form.post:
            class: Symfony\Component\Form\Form
            factory: ['@form.factory', createNamed]
            arguments: [post_name, 'NewsBundle\Form\PostType', null , { validation_groups: [Default] }]
    news.form.post_edit:
            class: Symfony\Component\Form\Form
            factory: ['@form.factory', createNamed]
            arguments: [post_edit_name, 'NewsBundle\Form\PostEditType', null , { validation_groups: [Default] }]
    news.type.comment:
            class: NewsBundle\Form\CommentType
            tags:
                - { name: form.type, alias: comment}
    news.type.post:
            class: NewsBundle\Form\PostType
            tags:
                - { name: form.type, alias: post}
    news.type.post_edit:
            class: NewsBundle\Form\PostEditType
            tags:
                - { name: form.type, alias: post_edit}